---
- hosts: docker
  become: true

  tasks:
   - name: docker_login
     docker_login:
               username: sanjivranjan123
               password: AzureVMAdmin123#
   - name: pull
     docker_image:
             name: sanjivranjan123/proj1:{{ImageTag}} 
   - name: create container
     docker_container:
             name: web
             image: sanjivranjan123/proj1:{{ImageTag}}
             state: started
             ports: 
                    "80:8080"
             tty: true
             detach: true
