---
- hosts: docker
  become: true

  tasks:
   - name: docker_login
     docker_login:
               username: vmadmin
               password: VMDocker#123
   - name: pull
     docker_image:
             name: sanjivranjan123/proj1:{{imagename}}
 
   - name: create container
     cocker_container:
             name: web
             image: sanjivranjan123/proj1:{{imagename}}
             state: started
             ports: 
                    "80:8080"
             tty: true
             detach: true

